#!/bin/bash

config="$HOME/.osc-project-statusrc"
if [ ! -f $config ]; then
    cat <<EOF >> $config
# Add your project/package/expectedversion (optional)
# configuration. In case package has a different version
# than expected, you will get notified.
#
# Example:
# obs_projects=(
#     some:project/packagename/version
#     some:another:project/anotherpackagename/1.2.3
#     and:so/on"
# )

obs_projects=()

EOF
fi

source $config

if [ "${#obs_projects[@]}" -eq "0" ]; then
    echo "Please add some projects into your configuration file at $config"
    exit 1;
fi

Y="\e[93m"
R="\e[31m"
HR="\e[91m"
G="\e[92m"
W="\e[97m"
D="\e[39m"

function display_help() {
    cat <<EOF
Usage: $(basename $0) [OPTION]
List status of the monitored projects in the OBS.

   -l, --list           list examined projects
   -h, --help           this help message

EOF
}

function get_patches_amount() {
    echo "$1" | grep 'patch$' | wc -l
}

function get_pkg_list() {
    project=$1
    package=$2
    echo "$(osc ls -e $project $package)"
}

function get_version() {
    project=$1
    package=$2
    echo "$(osc less $project/$package $package.spec | grep '^Version' | sed -e 's/.*\s//g')"
}

function list_projects() {
    for items in ${obs_projects[@]}; do
	IFS=$'/' read -r repo pkg version <<< "$items"
	echo -e "$Y$repo/$pkg$D ($G$version$D)"
    done
}

## Main
for items in ${obs_projects[@]}; do
    IFS=$'/' read -r repo pkg version <<< "$items"
    pkg_list=$(get_pkg_list $repo $pkg)
    pkg_patches=$(get_patches_amount "$pkg_list")
    pkg_version=$(get_version $repo $pkg)
    IFS=" | " read -ra pkg_log_items <<< "$(osc log $repo/$pkg | head -2 | grep -ve '---')"

    if [ -z "$version" ]; then
	VRC=$W
    else
	if [ "$version" == "$pkg_version" ]; then
	    VRC=$G
	else
	    VRC="$R \bexpected: $HR$version$R, current: $HR"
	fi
    fi

    if [ "$pkg_patches" -eq "0" ]; then
	VC=$G
    else
	VC=$R
    fi

    echo -e "$Y$repo/$pkg$D"
    printf "    Patches: $VC%s$D\n    Version: $VRC%s$D\n" $pkg_patches $pkg_version
    printf "   Revision: $W%s$D\nAccepted by: $W%s$D\nAccepted on: $W%s$D\n" \
	   ${pkg_log_items[0]} ${pkg_log_items[1]} "${pkg_log_items[2]} ${pkg_log_items[3]}"
done
