#!/bin/bash

ln -s ../git-format-pkg-patch gfp.py
ln -s ../osc-git-autopatch gpak.py
for fsrc in "test_gitpak_spec.py"; do
    python3 -m pytest $fsrc
done
rm -rf __pycache__
for lnk in "gfp" "gpak"; do
    rm "$lnk.py" 2> /dev/null
done
rm *.pyc 2> /dev/null
